### PR TITLE
Added python programs

### PR DESCRIPTION
**Pull request by animesh-77**
Added python programs for integer sequences
1) Sphenic number: https://en.wikipedia.org/wiki/Sphenic_number#:~:text=7%20References-,Definition,%2Dfree%203%2Dalmost%20primes.
2) radical of an integer : https://en.wikipedia.org/wiki/Radical_of_an_integer
3) Euler's zizag number : https://en.wikipedia.org/wiki/Alternating_permutation

### CODE REVIEW

**Comment by animesh-77** [comment]
Please look into this

**Comment by rahulcodes51** [comment]
Kardiya Bro🙂

**Comment by rahulcodes51** [comment]
Kardiya Bro

**Comment by animesh-77** [comment]
Thank you so much.

**Pull request merged**
